---
title: "NYPD Shooting Dataset"
author: "Z. Hall"
date: "2025-11-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(scales)

```

# Quick Exploratory Analysis for the NYPD Shooting Dataset

```{r import}
nypd_shooting <- read_csv("data/NYPD_Shooting_Incident_Data__Historic_.csv")
```

## Cleaning & Prep work for Analysis

```{r tidy}

nypd_shooting <- nypd_shooting %>% 
  mutate(OCCUR_DATE = mdy(OCCUR_DATE),
         year = year(OCCUR_DATE),
         month = month(OCCUR_DATE, label = TRUE),
         day_of_week = wday(OCCUR_DATE, label = TRUE),
         hour = hour(OCCUR_TIME))

hourly_shootings <- nypd_shooting %>%
  count(hour) %>%
  rename(shootings = n)

model_poly <- lm(shootings ~ poly(hour, 2), data = hourly_shootings)

```

## Analysis - (Final Chart includes Linear Model)

```{r Analysis}
nypd_shooting %>% count(hour) %>%
  ggplot(aes(x = hour, y = n)) +
  geom_col(fill = "steelblue") +
  scale_x_continuous(breaks = seq(0, 23, 2)) +
  labs(title = "Shootings by Hour of Day",
       x = "Hour (24hr)", y = "Number of Shootings")

nypd_shooting %>% count(year) %>%
  ggplot(aes(x = year, y = n)) +
  geom_line(color = "darkred", linewidth = 1) +
  geom_point(color = "darkred", size = 3) +
  labs(title = "Shooting Incidents All-Time",
       x = "Year", y = "Number of Shootings")

nypd_shooting %>% count(month) %>%
  ggplot(aes(x = month, y = n)) +
  geom_col(fill = "forestgreen") +
  labs(title = "Shootings by Month (Across All Years)",
       x = "Month", y = "Number of Shootings")

nypd_shooting %>% count(BORO, sort = TRUE) %>%
  ggplot(aes(x = reorder(BORO, n), y = n, fill = BORO)) +
  geom_col(show.legend = FALSE) + coord_flip() +
  labs(title = "Shootings by Borough", x = NULL, y = "Number of Shootings")

nypd_shooting %>% count(year, BORO) %>%
  ggplot(aes(x = year, y = n, color = BORO)) +
  geom_line(linewidth = 1) + geom_point(size = 2) +
  labs(title = "Shooting Trends by Borough", x = "Year",
       y = "Number of Shootings", color = "Borough")

hourly_shootings %>% mutate(predicted = predict(model_poly)) %>%
  ggplot(aes(x = hour, y = shootings)) +
  geom_point(size = 3, color = "darkred") +
  geom_line(aes(y = predicted), color = "steelblue", linewidth = 1) +
  labs(title = "Poly Model (Shootings Peak at Night)",
       subtitle = paste("R-squared:", round(summary(model_poly)$r.squared, 3)),
       x = "Hour", y = "Shootings")
```

## Bias
I'm not able to find any possible bias for this analysis, given how surface level this exploration was.